/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#5c647a",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b7c4ff",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#cad3ff",
        "outline-variant": "#c4c5d7",
        "primary-fixed": "#dce1ff",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#131b2e",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary": "#0037b0",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#3a485b",
        "surface-bright": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#3f465c",
        "outline": "#747686",
        "secondary": "#565e74",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#c7d6ee",
        "on-primary-fixed": "#001551",
        "on-tertiary-fixed": "#0d1c2e",
        "on-surface-variant": "#434655",
        "tertiary-fixed": "#d5e3fc",
        "on-primary-fixed-variant": "#0039b5",
        "tertiary-fixed-dim": "#b9c7df",
        "surface": "#f7f9fb",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "secondary-container": "#dae2fd",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#2151da",
        "inverse-primary": "#b7c4ff",
        "tertiary": "#374559",
        "tertiary-container": "#4f5d71",
        "primary-container": "#1d4ed8"
      },
      spacing: {
        "space-xl": "2.5rem",
        "margin": "1.5rem",
        "margin-lg": "3rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-lg": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "display": ["Newsreader", "serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "display-mobile": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        sans: ['Hanken Grotesk', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        "headline-sm": ["1.25rem", {"lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-lg": ["0.875rem", {"lineHeight": "1.25rem", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-lg": ["1.125rem", {"lineHeight": "1.75rem", "letterSpacing": "0", "fontWeight": "400"}],
        "body-sm": ["0.8125rem", {"lineHeight": "1.25rem", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-lg-mobile": ["1.75rem", {"lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "400"}],
        "label-md": ["0.75rem", {"lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "600"}],
        "body-md": ["0.9375rem", {"lineHeight": "1.5rem", "letterSpacing": "0", "fontWeight": "400"}],
        "headline-md": ["1.75rem", {"lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "500"}],
        "display": ["3rem", {"lineHeight": "3.5rem", "letterSpacing": "-0.025em", "fontWeight": "400"}],
        "label-sm": ["0.6875rem", {"lineHeight": "0.875rem", "letterSpacing": "0.06em", "fontWeight": "600"}],
        "display-mobile": ["2.25rem", {"lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "headline-lg": ["2.25rem", {"lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
