"""
test_hello_adk.py
------------------
Phase 1, Stage 1: Verification script for Google ADK setup.
Demonstrates creating a minimal ADK Agent, connecting it to an InMemorySessionService,
running it via ADK's Runner, and extracting the text response.
"""

import asyncio
from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

import config

async def run_hello_stage():
    # 1. Define the LLM Agent with name, Gemini model, and prompt instructions
    agent = Agent(
        name="hello_agent",
        model=config.DEFAULT_MODEL,
        instruction="You are a polite document intelligence assistant. Introduce yourself in 2 short sentences."
    )

    # 2. Instantiate an in-memory session manager to track conversation state
    session_service = InMemorySessionService()

    # 3. Create the ADK Runner, which bridges the Agent, session, and execution engine
    runner = Runner(
        agent=agent,
        app_name="hello_app",
        session_service=session_service
    )

    # 4. Create an active session thread for user "test_user"
    session = await session_service.create_session(
        app_name="hello_app",
        user_id="test_user"
    )

    # 5. Format the input message using Google GenAI Content and Part schema
    user_prompt = "Hello! What is your role?"
    user_message = types.Content(
        role="user",
        parts=[types.Part.from_text(text=user_prompt)]
    )

    print(f"--- [INPUT TO AGENT] ---")
    print(f"User ID: test_user")
    print(f"Session ID: {session.id}")
    print(f"User Prompt: '{user_prompt}'\n")

    print(f"--- [EXECUTING ADK RUNNER...] ---")
    response_text = ""
    async for event in runner.run_async(
        user_id="test_user",
        session_id=session.id,
        new_message=user_message
    ):
        # Extract response content events generated by the LLM
        if event.content and event.content.parts:
            for part in event.content.parts:
                if part.text:
                    response_text += part.text

    print(f"\n--- [OUTPUT FROM AGENT] ---")
    print(f"Agent Response:\n{response_text}\n")
    return user_prompt, response_text

if __name__ == "__main__":
    asyncio.run(run_hello_stage())
